name: Publish Wildfire Hockey GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy-github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout Wildfire Hockey Repo
        uses: actions/checkout@v4

      - name: Prepare Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.1

      - name: Install Wildfire Dependencies
        run: npm ci

      - name: Build Wildfire Page
        run: |
          npm run build
          touch build/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
