name: PR Requirements

on:
  pull_request:

jobs:
  pr-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wildfire Hockey Repo
        uses: actions/checkout@v4

      - name: Prepare Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Wildfire Hockey Dependencies
        run: npm ci

      - name: Check Linting
        run: npm run lint
