name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wildfire Hockey Repo
        uses: actions/checkout@v4

      - name: Prepare Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Install Wildfire Hockey Dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Wildfire Hockey Tests
        run: npm run test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results.xml
          path: test-results
